### ISSUE TITLE
Backgroud Music Hack Doesn't Work with DraStic or PPSSPP.

### ISSUE THREAD

**Issue by MajorDangerNine** [Shakz76/Eazy-Hax-RetroPie-Toolkit#1]
When DraStic or PPSSPP are launched, the background music does not stop.

Is there anyway this could be automatic like it is for Reicast or Mupen64plus? I'd rather not have to manually disable the background music.

**Comment by Shakz76** [comment]
Fixed with latest release. Please update, remove BGM, add it back, and let me know. 
Thanks for reporting it! 
-Forrest/ezhx

**Comment by Eckaji** [comment]
Did as you said, and now it works properly for DraStic, but PPSSPP still doesn't have the music stop for it. Also, when I say PPSSPP, I mean the standalone one as the libretro version does have the music properly stop for it.

Really seems like it should work for PPSSPP from looking at the commit, though I barely understand how that stuff works. If it works for you then I'll try fiddling around with my setup more.

Welcome for the report.

**Comment by Shakz76** [comment]
Ok I added psp along with ppsspp and lr-ppsspp...hopefully the script will catch it now and stop bgm. 
same as before...
[https://github.com/Shakz76/Eazy-Hax-RetroPie-Toolkit/commit/4dc9534527cb78c3d7cb3acad4c1ddc5e862b64f](url)
